[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc = "0.8.19"

# optimizer settings for debugging
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# optimizer settings for snapshotting.
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 5096