name: MetaBoard Subgraph CI
on: [push]
env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Initialize subgraph dependencies
        working-directory: ./subgraph
        run: nix run .#init

      - name: Start docker container
        working-directory: ./subgraph
        run: nix run .#docker-up

      - name: Run Subgraph tests
        working-directory: ./subgraph
        run: nix run .#ci-test

      - name: Stop containers
        working-directory: ./subgraph
        run: nix run .#docker-down
